### ISSUE TITLE
Blueprints with user-defined C++ parents still become unlinked

### ISSUE THREAD

**Issue by andgeno** [SamCarey99/UE4-Tools#2]
I tried v1.1.1 with a test project and it unlinked my Blueprints. Maybe there are more edge cases?

The unlinked BPs have the project's name in the middle of their name like so:

Project Name = `TEST_CPP`
Blueprint Name: `BP_TEST_CPP_GameMode`

**Comment by SamCarey99** [comment]
Right, that was not something I considered. I will take a look soon and fix it.

**Comment by SamCarey99** [comment]
I have be trying to replicate this issues but cannot. It may have been caused by something else. Did you rename the project or class multiple times without reloading the project?

**Comment by andgeno** [comment]
As far as I remember I just renamed that test project once and tried to open it directly after that. If I encounter this issue again, I will let you know. You can probably close this issue for now.
