### ISSUE TITLE
Rename c++ class doesn't rename cpp file with Private / Public folder structure

### ISSUE THREAD

**Issue by mklabs** [SamCarey99/UE4-Tools#4]
Thank you for UE4-Tools! Looks like a really nice project!

I have however a little feature request to be able to properly rename the cpp file in a folder structure with Private / Public directories, which is pretty common in UE4 projects and plugins.

Here I renamed an `ASTCheatManager` class to `GSCCheatManager`, the `.cpp` file content gets updated properly, but not its filename:

![image](https://user-images.githubusercontent.com/113832/114576152-2a542480-9c7b-11eb-8785-5dbd21a0fa95.png)

It also appears the ActiveClassRedirects in config are not done either in this case.

I can still rename the filename by hand, but would be nice if it was supported by the tool.

**Comment by mklabs** [comment]
Also, the source files are from a plugin, not project files. I don't know if it has any importance.

**Comment by SamCarey99** [comment]
Thanks for the report. This issue has now been fixed in version 5.1

**Comment by mklabs** [comment]
Awesome! I have another kind of feature request if you don't mind, I'm gonna open up another issue for it.

**Comment by SamCarey99** [comment]
Yeah, thats fine. I'm always interested in new ideas.
